const INDUSTRIES = {
 service:{name:'サービス',icon:'✦',pain:['提案・見積の作成が遅い','顧客対応が担当者頼み','議事録から次の行動につながらない'],tasks:['提案・見積の下書き','社内FAQ・顧客対応支援','議事録から対応リスト作成'],kpi:['提案までの日数・受注率','回答時間・対応漏れ件数','フォロー実施率'],example:'顧客の要望と過去提案を比較し、営業責任者が提案内容を決めています。'},
 realestate:{name:'不動産',icon:'⌂',pain:['物件提案に時間がかかる','契約書類の確認負担が大きい','問い合わせの返信が遅れる'],tasks:['条件に合う物件の比較表','契約書の確認項目抽出','問い合わせ回答案'],kpi:['提案時間・内見化率','確認時間・差し戻し件数','初回返信時間'],example:'顧客条件を物件一覧と照合し、担当者が内見候補を選びます。契約の最終確認は専門担当者が行います。'},
 manufacturing:{name:'製造',icon:'⚙',pain:['見積・原価判断が属人化','品質トラブルの過去情報が見つからない','保全記録を活用できない'],tasks:['過去見積・原価の比較支援','品質ナレッジ検索','保全記録の要約・照会'],kpi:['見積所要時間・案件粗利率','調査時間・再発件数','確認時間・停止時間'],example:'過去の類似案件と材料費をExcelで比較し、工場長が見積価格を承認しています。'},
 wholesale:{name:'卸売・商社',icon:'▦',pain:['メール受注の転記が多い','在庫・納期確認が遅い','営業提案の準備が重い'],tasks:['受注内容の抽出・確認','在庫・納期照会支援','得意先別の提案下書き'],kpi:['処理時間・転記ミス','回答時間・失注件数','提案件数・粗利率'],example:'受注メールと在庫表を見比べ、営業担当が納期と代替品を判断しています。'},
 retail:{name:'小売',icon:'▱',pain:['販促づくりに手が回らない','店舗の問い合わせが集中','発注・在庫判断が難しい'],tasks:['商品別の販促案作成','店舗スタッフFAQ','販売・在庫データの比較'],kpi:['制作時間・販促経由売上','問い合わせ件数・回答時間','欠品件数・廃棄額'],example:'店舗ごとの売上と在庫を見て、店長が発注量を決めています。'},
 logistics:{name:'運輸・倉庫',icon:'⇄',pain:['配車調整の情報が散在','日報・請求作業が重い','配送問い合わせが多い'],tasks:['配車条件の整理支援','日報・請求データの抽出','配送状況の回答支援'],kpi:['調整時間・待機時間','処理時間・確認ミス','回答時間・対応漏れ'],example:'配送依頼と車両・担当者の予定を比較し、配車担当者が運行計画を確認しています。'},
 construction:{name:'建設',icon:'△',pain:['現場報告・写真整理が重い','積算の比較に時間がかかる','安全書類の確認が煩雑'],tasks:['現場報告の下書き','過去積算・原価の比較','安全書類の確認項目抽出'],kpi:['報告時間・残業時間','見積時間・工事粗利率','確認時間・差し戻し件数'],example:'現場写真と作業日報をもとに、現場責任者が進捗と追加工事を判断しています。'},
 agriculture:{name:'農林水産',icon:'♧',pain:['作業記録を残す負担','販路開拓に手が回らない','申請資料の作成が大変'],tasks:['作業記録の整理','商品紹介・販路提案','申請書の下書き支援'],kpi:['記録時間・記録率','問い合わせ数・粗利','作成時間・差し戻し'],example:'出荷実績と作業記録を見て、生産者が出荷先と作業計画を決めます。'},
 finance:{name:'金融・保険',icon:'▥',pain:['規程検索に時間がかかる','面談記録の整理が負担','説明資料の準備が重い'],tasks:['承認済み規程の検索','面談記録の要点整理','説明資料の下書き'],kpi:['検索時間・根拠確認率','記録時間・対応漏れ','準備時間・レビュー修正数'],example:'承認済み規程を確認し、管理者が提案可否を判断します。与信等の最終判断は人が行います。'},
 hospitality:{name:'宿泊・飲食',icon:'☕',pain:['予約問い合わせが多い','販促・メニューづくりが負担','引き継ぎがうまくいかない'],tasks:['予約問い合わせ回答案','販促・メニュー説明作成','引き継ぎ情報の要約'],kpi:['返信時間・予約転換率','制作時間・客単価','確認時間・対応漏れ'],example:'予約メールと空き状況を見て、担当者が予約案内を作成しています。'},
 healthcare:{name:'医療・介護',icon:'＋',pain:['事務記録に時間がかかる','規程・マニュアルが探しにくい','申し送りの負担が大きい'],tasks:['匿名化した事務記録の整理','業務マニュアル検索','事務連絡の要点整理'],kpi:['記録時間・差し戻し','検索時間・確認率','引き継ぎ時間・漏れ件数'],example:'管理者が事務記録とマニュアルを確認しています。診療・ケアの判断は対象にしません。'},
 other:{name:'その他',icon:'⋯',pain:['書類づくりに時間がかかる','社内の情報が見つからない','情報の転記・確認が多い'],tasks:['書類の下書き','社内ナレッジ検索','入力内容の抽出・比較'],kpi:['作成時間・修正回数','検索時間・回答精度','処理時間・ミス件数'],example:'担当者が資料を探して比較し、責任者が最終判断しています。'}
};
let flowStep=0;
const fields=['clientIndustry','clientGoal','clientDecision','clientFrequency','clientMinutes','clientPeople','clientRate','clientOwner','clientRisk','clientData','clientStage','clientBarrier','clientTarget','clientSystem','clientTraining','clientUrgency'];
function setupIndustryFlow(){
 const form=$('diagnosisForm');
 form.innerHTML=`<nav class="flow-steps" aria-label="診断の進捗"><span>01 業種</span><span>02 悩み</span><span>03 現状</span><span>04 準備</span></nav>
 <section class="flow-page" data-step="0"><span class="eyebrow">YOUR BUSINESS</span><h2>あなたの業種から、始めましょう。</h2><p>近い業種を選ぶと、現場の悩みに合う診断に変わります。</p><input type="hidden" id="clientIndustry"><div id="industryCards" class="industry-cards">${Object.entries(INDUSTRIES).map(([key,v])=>`<button type="button" data-industry="${key}" aria-pressed="false"><i>${v.icon}</i><strong>${v.name}</strong><small>${v.tasks[0]}</small></button>`).join('')}</div><p class="field-help">複数事業がある場合は、今回改善したい事業を選択してください。</p></section>
 <section class="flow-page hidden" data-step="1"><span class="eyebrow">YOUR CHALLENGE</span><h2>今、何に困っていますか？</h2><p id="industryIntro"></p><fieldset><legend>最初に解決したい悩みを1つ選択</legend><div id="painChoices" class="pain-choices"></div></fieldset><label>経営として実現したいこと<select id="clientGoal"><option value="">選択してください</option><option value="sales">売上・受注機会を増やす</option><option value="margin">粗利・利益を改善する</option><option value="productivity">人手不足・残業を減らす</option><option value="quality">品質・対応精度を安定させる</option></select></label><label>普段、誰がどの資料で何を判断していますか？<textarea id="clientDecision" maxlength="2000" rows="4"></textarea></label><button type="button" id="useExample" class="text-action">業種の記入例を使う</button><label>こうなれば成功、という目標（任意）<input id="clientTarget" maxlength="200" placeholder="例：翌日までに見積を返し、受注機会を逃さない"></label></section>
 <section class="flow-page hidden" data-step="2"><span class="eyebrow">CURRENT WORKFLOW</span><h2>いまの負担を、数字にしましょう。</h2><p>選んだ1業務だけで構いません。おおよその数値でも、後から変更できます。</p><div class="two-col"><label>月間件数<input id="clientFrequency" type="number" min="1" max="100000" placeholder="例：20"></label><label>1件・1人あたりの時間（分）<input id="clientMinutes" type="number" min="1" max="10000" placeholder="例：30"></label><label>1件に関わる人数<input id="clientPeople" type="number" min="1" max="1000" value="1"></label><label>時間単価（円・試算用）<input id="clientRate" type="number" min="0" max="100000" value="3000"></label></div><div id="liveWorkload" class="live-workload" aria-live="polite"></div><fieldset><legend>判断に使う資料（複数可）</legend><div class="check-grid">${['Excel','PDF','メール','基幹','紙','CRM'].map(v=>`<label><input type="checkbox" name="clientMaterial" value="${v}"><span>${v}</span></label>`).join('')}</div></fieldset><label>現在のAI・DX活用<select id="clientStage"><option value="">選択してください</option><option value="1">紙・手作業が中心</option><option value="2">Excel・SaaSを使うが、情報は分散</option><option value="3">個人でAIを利用している</option><option value="4">業務フローにAIを組み込んでいる</option></select></label></section>
 <section class="flow-page hidden" data-step="3"><span class="eyebrow">READY FOR A SMALL START</span><h2>小さく試すための準備を確認。</h2><label>導入にあたって、最も気になること<select id="clientBarrier"><option value="">選択してください</option><option>費用対効果がわからない</option><option>使える人・時間が足りない</option><option>情報漏えい・誤回答が心配</option><option>既存システムとの連携が心配</option><option>何から始めるかわからない</option></select></label><div class="two-col"><label>業務データの準備<select id="clientData"><option value="">選択してください</option><option value="1">紙・個人の記憶が中心</option><option value="3">電子化済みだが分散</option><option value="5">整理済み・サンプルを準備できる</option></select></label><label>推進責任者<select id="clientOwner"><option value="">選択してください</option><option value="1">まだ未定</option><option value="3">候補はいる</option><option value="5">決まっている</option></select></label><label>主なデータ・システム<select id="clientSystem"><option value="">選択してください</option><option>紙・Excel・メール</option><option>SaaSが複数に分散</option><option>基幹・業務システム</option><option>CSVでサンプルを用意できる</option></select></label><label>導入・活用の研修体制<select id="clientTraining"><option value="">選択してください</option><option>まだ考えていない</option><option>利用ルールと現場研修が必要</option><option>責任者・現場の研修担当を決められる</option></select></label></div><label>扱う情報の機密性<select id="clientRisk"><option value="">選択してください</option><option value="2">公開情報・匿名化データで試せる</option><option value="3">社内情報を含むため確認が必要</option><option value="5">個人情報・機密情報・規制に関わる</option></select></label><label>いつまでに最初の効果を確認したいですか？<select id="clientUrgency"><option value="">選択してください</option><option>今月〜3か月以内</option><option>半年以内</option><option>まず情報収集</option></select></label><label class="client-save-option"><input id="clientShare" type="checkbox"><span>診断の要約を案内元・連携パートナー画面に表示する（この端末のデモ内）</span></label><p class="field-help">回答全文は共有せず、業種・優先業務・効果仮説・次の確認事項を表示します。</p></section>
 <p id="flowError" role="alert" class="form-error"></p><div class="flow-actions"><button id="flowBack" type="button" class="btn secondary">戻る</button><button id="flowNext" type="button" class="btn primary">次へ進む →</button><button id="flowSubmit" type="submit" class="btn primary hidden">AI経営実装カルテを見る →</button></div><label class="client-save-option"><input id="clientRemember" type="checkbox"><span>この端末に入力途中を保存する</span></label>`;
 document.querySelectorAll('[data-industry]').forEach(b=>b.onclick=()=>selectIndustry(b.dataset.industry));
 $('flowNext').onclick=()=>{if(validateStep()){flowStep++;showFlowStep();}};
 $('flowBack').onclick=()=>{flowStep=Math.max(0,flowStep-1);showFlowStep();};
 $('useExample').onclick=()=>{$('clientDecision').value=INDUSTRIES[$('clientIndustry').value].example;saveClientDraft();};
 form.addEventListener('input',()=>{updateClientProgress();saveClientDraft();});
 form.addEventListener('change',saveClientDraft);
 showFlowStep(false);
}
function selectIndustry(key,pain=''){
 $('clientIndustry').value=key;const v=INDUSTRIES[key];if(!v)return;
 document.querySelectorAll('[data-industry]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.industry===key)));
 $('industryIntro').textContent=v.name+'の業務を、売上・利益・時間の視点で整理します。';
 $('clientDecision').placeholder=v.example;
 $('painChoices').innerHTML=v.pain.map((p,i)=>`<label><input type="radio" name="clientPain" value="${i}" ${String(i)===String(pain)?'checked':''}><span>${p}</span></label>`).join('');
 updateClientProgress();
}
function showFlowStep(scroll=true){document.querySelectorAll('.flow-page').forEach(p=>p.classList.toggle('hidden',Number(p.dataset.step)!==flowStep));document.querySelectorAll('.flow-steps span').forEach((s,i)=>s.classList.toggle('active',i===flowStep));$('flowBack').classList.toggle('hidden',flowStep===0);$('flowNext').classList.toggle('hidden',flowStep===3);$('flowSubmit').classList.toggle('hidden',flowStep!==3);$('flowError').textContent='';document.querySelector('.step-label').textContent=`STEP ${flowStep+1} / 4`;if(scroll)$('diagnosisForm').scrollIntoView({behavior:'smooth',block:'start'});}
function validateStep(){
 const required=[['clientIndustry'],['clientGoal','clientDecision'],['clientFrequency','clientMinutes','clientPeople','clientRate','clientStage'],['clientBarrier','clientData','clientOwner','clientRisk','clientSystem','clientTraining','clientUrgency']][flowStep];
 for(const id of required){const el=$(id);if(!el.value.trim()||!el.checkValidity()){ $('flowError').textContent='未入力・入力範囲を確認してください。';el.focus();return false;}}
 if(flowStep===1&&!document.querySelector('[name="clientPain"]:checked')){$('flowError').textContent='最初に解決したい悩みを選択してください。';return false;}
 if(flowStep===2&&!document.querySelector('[name="clientMaterial"]:checked')){$('flowError').textContent='判断に使う資料を選択してください。';return false;}return true;
}
function clientDraft(){return {...Object.fromEntries(fields.map(id=>[id,$(id).value])),pain:document.querySelector('[name="clientPain"]:checked')?.value??'',materials:Array.from(document.querySelectorAll('[name="clientMaterial"]:checked'),e=>e.value),remember:$('clientRemember').checked,share:$('clientShare').checked};}
function saveClientDraft(){if(!currentAccount)return;try{const d=clientDraft();const key=DRAFT_PREFIX+currentAccount.username;if(d.remember)localStorage.setItem(key,JSON.stringify(d));else localStorage.removeItem(key);}catch{showToast('この端末には保存できません。診断は続けられます。');}}
function updateClientProgress(){const d=clientDraft();$('clientProgress').textContent=Math.round(fields.filter(id=>d[id]!=='').length/fields.length*100)+'%';const h=Number(d.clientFrequency)*Number(d.clientMinutes)*Number(d.clientPeople)/60;$('liveWorkload').textContent=h>0?`いま、この業務に月 ${h.toLocaleString('ja-JP',{maximumFractionDigits:1})} 人時。どこを減らせるか、次に確認します。`:'件数・時間・人数を入力すると、月間の業務負担が見えます。';}
function renderClient(){let d={};try{d=JSON.parse(localStorage.getItem(DRAFT_PREFIX+currentAccount.username)||'{}');}catch{};if(INDUSTRIES[d.clientIndustry])selectIndustry(d.clientIndustry,d.pain);fields.forEach(id=>{if(d[id]!==undefined)$(id).value=d[id];});document.querySelectorAll('[name="clientMaterial"]').forEach(e=>e.checked=(d.materials||[]).includes(e.value));$('clientRemember').checked=!!d.remember;$('clientShare').checked=!!d.share;updateClientProgress();let cases=[];try{cases=JSON.parse(localStorage.getItem(CASES_KEY)||'[]');}catch{};const own=cases.find(x=>x.ownerAccount===currentAccount.username);if(own)showClientResult(own);}
function calculateClientCase(d){const base=Number(d.clientFrequency)*Number(d.clientMinutes)*Number(d.clientPeople)/60;const axes=[Math.min(20,Math.round(Number(d.clientFrequency)/2)),Number(d.clientData)*4,Number(d.clientOwner)*4,Number(d.clientStage)*5,Number(d.clientRisk)===5?4:Number(d.clientRisk)===3?12:20];const score=axes.reduce((a,b)=>a+b,0);const gated=Number(d.clientRisk)===5||Number(d.clientData)===1||Number(d.clientOwner)===1;const v=INDUSTRIES[d.clientIndustry];const idx=Number(d.pain);const low=base*.2,high=base*.4;return{score,axes,base,low,high,status:gated?'meeting':'poc',priority:v.tasks[idx],hours:`${low.toFixed(1)}〜${high.toFixed(1)}h/月`,risk:Number(d.clientRisk)===5?'高：専門確認':Number(d.clientRisk)===3?'中：要確認':'低：標準確認',next:gated?'責任者・データ・情報管理の準備を面談で確認':'匿名化サンプル20件で試し、現状と比較する',kpi:v.kpi[idx],securityPlan:Number(d.clientRisk)===5?'入力禁止情報・保管先・権限・ログ・人の承認を要件化':Number(d.clientRisk)===3?'匿名化、アクセス権限、利用ルール、出力レビューを先に決める':'利用ルールと最低限のレビュー手順を決める',trainingPlan:d.clientTraining==='まだ考えていない'?'AIの基礎・プロンプト・誤回答確認・情報管理を90分研修':d.clientTraining==='利用ルールと現場研修が必要'?'責任者向け運用研修＋現場の実務演習を実施':'責任者の運用研修と現場の短時間演習を実施'};}
function submitClientDiagnosis(e){e.preventDefault();for(let i=0;i<4;i++){flowStep=i;if(!validateStep()){showFlowStep(false);validateStep();return;}}const d=clientDraft(),r=calculateClientCase(d),now=new Date();const item={...r,id:'AIC-'+now.toISOString().slice(0,10).replaceAll('-','')+'-'+randomId(),company:currentAccount.organization,industry:INDUSTRIES[d.clientIndustry].name,industryKey:d.clientIndustry,institutionKey:currentAccount.institutionKey,ownerAccount:currentAccount.username,createdAt:now.toISOString(),updatedAt:now.toISOString(),decision:d.clientDecision,materials:d.materials,draft:d,shareConsent:d.share,version:'industry-v3',summary:`${INDUSTRIES[d.clientIndustry].pain[Number(d.pain)]}。優先業務：${r.priority}。確認する指標：${r.kpi}。`,statusLabel:statusLabel(r.status)};try{let a=JSON.parse(localStorage.getItem(CASES_KEY)||'[]');a=a.filter(x=>x.ownerAccount!==currentAccount.username);a.unshift(item);localStorage.setItem(CASES_KEY,JSON.stringify(a));localStorage.removeItem(DRAFT_PREFIX+currentAccount.username);}catch{showToast('端末保存ができません。カルテをダウンロードしてください。');}showClientResult(item);$('clientResult').scrollIntoView({behavior:'smooth'});}
function downloadChart(item){const b=new Blob([JSON.stringify(item,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=item.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function showClientResult(item){const root=$('clientResult');root.classList.remove('hidden');const d=item.draft||{},v=INDUSTRIES[item.industryKey]||INDUSTRIES.other;const selected=Number(d.pain||0);const order=[selected,...[0,1,2].filter(i=>i!==selected)];const readiness=item.axes||[10,10,10,10,10];const money=n=>Math.round(n).toLocaleString('ja-JP');const barrier=d.clientBarrier||'何から始めるかわからない';const responses={'費用対効果がわからない':'1業務の実績を測り、月額費用と比較してから継続を判断します。','使える人・時間が足りない':'責任者1名・週30分の振り返りから開始。現場担当者と一緒に確認します。','情報漏えい・誤回答が心配':'匿名化サンプルで試し、根拠の表示と人の承認を必須にします。','既存システムとの連携が心配':'まずCSVや既存資料で試し、効果確認後にシステム接続を検討します。','何から始めるかわからない':'今回選んだ悩みの1業務から始め、改善指標を1つ決めます。'};
 root.innerHTML=`<div class="chart-top"><div><span class="eyebrow">YOUR AI IMPLEMENTATION CANVAS</span><h2>${esc(item.industry)}のAI経営実装カルテ</h2><p>${esc(item.company)} · ${esc(item.id)}</p></div><span class="chart-badge">${item.status==='poc'?'小さな実証へ':'準備を整えて実証へ'}</span></div><div class="chart-summary"><div><small>最初に試したい業務</small><h3>${esc(item.priority)}</h3><p>${esc(item.summary)}</p><strong>確認する成果：${esc(item.kpi||'処理時間・確認ミス')}</strong></div><div class="readiness"><strong>${item.score}<small>/100</small></strong><span>実証準備度（独自目安）</span></div></div>
 <div class="chart-columns"><section><h3>いまの自社を把握する</h3><p>目標：${esc(d.clientTarget||'面談で具体的な目標値を決める')}</p><p>現状の判断：${esc(item.decision||'過去の診断データ')}</p>${['業務の反復性','データ準備','推進体制','デジタル活用','情報管理の準備'].map((t,i)=>`<div class="axis"><span>${t}</span><meter min="0" max="20" value="${readiness[i]}"></meter><b>${readiness[i]}/20</b></div>`).join('')}<details><summary>評価方法を見る</summary><p>反復性：月件数÷2（上限20）。データ準備・責任者：各選択値1/3/5×4。活用段階：1〜4×5。情報管理：低20・要確認12・高4。実装効果や採択確率ではなく、面談の優先確認に使う目安です。</p></details></section><section class="benefit-box"><span class="eyebrow">MAKE THE VALUE VISIBLE</span><h3>取り戻せる時間の仮説</h3><div class="benefit-number">${esc(item.hours)}</div><p>現状 ${Number(item.base||0).toFixed(1)} 人時/月 × 削減率20〜40%（仮定）</p><p>年間の時間価値：<strong>${money((item.low||0)*Number(d.clientRate||0)*12)}〜${money((item.high||0)*Number(d.clientRate||0)*12)}円</strong></p><small>件数×1人あたり分数×人数÷60で算出。時間価値は人件費削減・利益増加そのものではありません。売上・粗利への影響は実証で別途計測します。</small><label>検討する月額費用（円・任意）<input id="compareCost" type="number" min="0" max="10000000" placeholder="見積取得後に入力"></label><p id="costComparison" aria-live="polite">初期費用・教育・運用工数も含めて判断しましょう。</p></section></div>
 <h3>AI化の候補 TOP 3</h3><div class="opportunity-grid">${order.map((n,i)=>`<article><span>0${i+1} ${i===0?'今回の推奨':'次の拡張候補'}</span><h4>${v.tasks[n]}</h4><p>${v.pain[n]}</p><small>検証指標：${v.kpi[n]}</small><div class="mini-flow">資料を読む → AIが整理 → 人が承認</div></article>`).join('')}</div>
 <div class="barrier-answer"><strong>「${esc(barrier)}」への進め方</strong><p>${responses[barrier]||responses['何から始めるかわからない']}</p></div>
 <section class="agent-experience"><span class="eyebrow">TRY BEFORE YOU DECIDE</span><h3>AIが仕事を進める様子を、体感する。</h3><p>別サイトの実務デモで「${esc(item.priority)}」に近い業務を選び、入力→処理→人の確認を体験してください。診断の回答はデモへ送信しません。</p><div class="detail-actions"><button class="btn primary" id="loadAgent" type="button">このページでAIエージェントを体験 →</button><a class="btn secondary" href="https://c7313y-rgb.github.io/ai-agent-demo/" target="_blank" rel="noopener noreferrer">別タブで開く ↗</a></div><div id="agentFrame"></div><p class="field-help">サンプルによる実務体験です。自社の本番システムには接続しません。表示できない場合は別タブでお試しください。</p></section>
 <h3>90日間で、続けるかを判断する</h3><div class="roadmap"><article><b>01–30日</b><h4>業務と基準をそろえる</h4><p>${esc(item.next)}。責任者を決め、${esc(item.kpi||'処理時間')}の現状値を記録。</p></article><article><b>31–60日</b><h4>1業務だけ試す</h4><p>AIの下書きを担当者が確認。修正時間・誤り・利用率を毎週記録。</p></article><article><b>61–90日</b><h4>効果と費用で判断</h4><p>品質を維持できたか、費用を上回る価値があるかを確認し、拡張・改善・中止を決めます。</p></article></div>
 <section class="next-decision"><h3>次の一歩を、選びましょう。</h3><p>提供：${esc(CONFIG.provider?.name||'株式会社RCG')}。案内元とカルテを見ながら、無理のない試行範囲を相談できます。</p><div class="detail-actions"><button class="btn primary" id="prepareConsult" type="button">相談用のメモを作る</button><button class="btn secondary" id="clientPrintBtn" type="button">カルテを印刷 / PDF保存</button><button class="btn secondary" id="chartJson" type="button">JSON保存</button></div><div id="consultMemo" class="hidden"></div><p class="field-help">相談メモの作成は申込み・送信ではありません。共有は${item.shareConsent?'この端末のデモ画面内で許可済み':'未許可（自社のカルテのみ）'}です。</p></section>`;
 $('clientPrintBtn').onclick=()=>{document.body.classList.add('chart-print');printActiveView();setTimeout(()=>document.body.classList.remove('chart-print'),1200);};$('chartJson').onclick=()=>downloadChart(item);
 $('loadAgent').onclick=()=>{$('agentFrame').innerHTML='<iframe title="AIエージェント実務デモ" src="https://c7313y-rgb.github.io/ai-agent-demo/" loading="lazy" referrerpolicy="no-referrer"></iframe>';$('loadAgent').textContent='デモを再読み込み';};
 $('compareCost').oninput=()=>{const cost=Number($('compareCost').value);$('costComparison').textContent=$('compareCost').value?`月間時間価値から月額費用を引いた参考額：${money((item.low||0)*Number(d.clientRate||0)-cost)}〜${money((item.high||0)*Number(d.clientRate||0)-cost)}円。初期費用等は別途。`:'初期費用・教育・運用工数も含めて判断しましょう。';};
 $('prepareConsult').onclick=()=>{$('consultMemo').classList.remove('hidden');$('consultMemo').innerHTML=`<h4>案内元との面談に持参するメモ</h4><p>テーマ：${esc(item.priority)}<br>悩み：${esc(v.pain[selected])}<br>指標：${esc(item.kpi||'処理時間')}<br>次の確認：${esc(item.next)}<br>持参するもの：匿名化サンプル20件・現在の処理時間・担当者候補。費用と支援範囲は個別相談。補助制度は対象経費・公募要件を確認します。</p>`;};
}
